# Generated by Django 2.2.1 on 2019-05-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colonias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colonias.Colonias')),
            ],
        ),
    ]
