# Generated by Django 2.2.1 on 2019-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='user',
            field=models.IntegerField(default=1, verbose_name=11),
            preserve_default=False,
        ),
    ]
