# Generated by Django 2.2.1 on 2019-05-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20190531_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='user',
            new_name='usuario',
        ),
    ]
