# Generated by Django 2.2.1 on 2019-05-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=50)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicaciones.Publicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='comentarios_publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comentarios.Comentarios')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicaciones.Publicaciones')),
            ],
        ),
    ]
