# Generated by Django 2.2.1 on 2019-05-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20190531_1218'),
        ('Comentarios', '0002_comentarios_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='user',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios'),
            preserve_default=False,
        ),
    ]
